modLoader="javafml"

loaderVersion="[43,)"

license="MIT"

[[mods]]

modId="mangomilk_building"

version="${file.jarVersion}"

displayName="Create: MangoMilk Building"

logoFile="logo.png"


authors="DrMangoTea, Milky"

description='''
dave's building extended but way better
'''

[[dependencies.mangomilk_building]]

    modId="forge"

    mandatory=true

    versionRange="[43,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.mangomilk_building]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
